# Python Practice

###########################################################################################################################

# 1. Using python as a calculator

## Numbers

In [1]:
2+1

3

In [2]:
2-1

1

In [3]:
1-1

0

In [4]:
-1-2

-3

In [5]:
6*3

18

In [6]:
6/3

2.0

In [7]:
(50-(2*8))/2

17.0

In [8]:
17%3

2

In [9]:
5*3+2

17

In [10]:
5**2

25

In [11]:
5**3

125

In [12]:
2**4

16

In [13]:
w=20
x=25
w+x

45

In [14]:
w=25
x=45
sum=w+x
sum

70

In [15]:
12.56*14.26

179.1056

In [16]:
tax = 12.5 / 100
price = 100.50
price * tax

12.5625

In [17]:
price + _ #here the last printed value will be stored to the variable _ 

113.0625

In [18]:
round(_,2) #roundoff the last printed value

113.06

In [19]:
round(_)

113

## Strings

In [20]:
'spam eges'

'spam eges'

In [21]:
"rajkamal"

'rajkamal'

In [22]:
'"yes". They said'

'"yes". They said'

In [23]:
print("Hello world")

Hello world


In [24]:
i = 256*256
print('The value of i is', i)

The value of i is 65536


In [25]:
s = "India"

In [26]:
s

'India'

In [27]:
print(s)

India


In [28]:
r= "i am a good boy \n i am not a good boy"

In [29]:
r

'i am a good boy \n i am not a good boy'

In [30]:
print(r)

i am a good boy 
 i am not a good boy


In [31]:
r="********\n********"

In [32]:
print(r)

********
********


In [33]:
r="**********\n**********"
s="***    ***"
print(r)
print(s)

**********
**********
***    ***


In [34]:
print('C:\some\name')  # here \n means newline!

C:\some
ame


In [35]:
print(r'C:\some\name') # note the r before the quote

C:\some\name


In [36]:
print("""\
****************
****************
****        ****
****        ****
****************
****************
****************
***** *********
*****   ********
*****    ********
*****      ********
*****         ********
*****           ********

""")    #can write anything in print with thriple quotes

****************
****************
****        ****
****        ****
****************
****************
****************
***** *********
*****   ********
*****    ********
*****      ********
*****         ********
*****           ********




###  String Concatination

In [37]:
"raj"+"kamal"

'rajkamal'

In [38]:
"raj "*3

'raj raj raj '

In [39]:
"raj "*3 + "kamal "*2

'raj raj raj kamal kamal '

In [40]:
'raj' 'kamal' 'b gowda'#useful for very long strigs

'rajkamalb gowda'

In [41]:
'raj' ' kamal'

'raj kamal'

In [42]:
long_string = (" When i was a child ,i was eating mangoes very much but suddenly i stooped eating everything because my"
                " mom said not to eat")

In [43]:
long_string

' When i was a child ,i was eating mangoes very much but suddenly i stooped eating everything because my mom said not to eat'

In [44]:
x="raj"

In [45]:
x+ 'kamal'

'rajkamal'

In [46]:
x + " malotra"

'raj malotra'

In [47]:
x+ " bahaddur"

'raj bahaddur'

### Indexing

In [48]:
string = "Data Science"

In [49]:
string[0]

'D'

In [50]:
string[1]

'a'

In [51]:
string[4]

' '

In [52]:
string[5]

'S'

In [53]:
string[-1]

'e'

In [54]:
string[-4]

'e'

In [55]:
string[-12]

'D'

In [56]:
string[-7]

'S'

### Sclicing

In [57]:
x="I am the king of the world"

In [58]:
x[0]

'I'

In [59]:
x[0:]

'I am the king of the world'

In [60]:
x[0:2]

'I '

In [61]:
x[0:5]

'I am '

In [62]:
x[9:13]

'king'

In [63]:
x[21:26]

'world'

In [64]:
x[:8]

'I am the'

In [65]:
x[:]

'I am the king of the world'

In [66]:
x[:6] + x[6:]

'I am the king of the world'

In [67]:
x[:9] + x[9:]

'I am the king of the world'

In [68]:
x[-5:-1]

'worl'

In [69]:
x[-5:]

'world'

In [70]:
x[-9:]

'the world'

In [71]:
x[-17:]

'king of the world'

In [72]:
x[35]

IndexError: string index out of range

In [73]:
x[5:35]

'the king of the world'

In [74]:
x[35:] #empty string

''

In [75]:
word="Python"

In [76]:
word[0]='J' #immutable

TypeError: 'str' object does not support item assignment

In [77]:
word[2:6]='Dra'

TypeError: 'str' object does not support item assignment

In [78]:
word[1:6]+'J'

'ythonJ'

In [79]:
'J'+ word[1:6]

'Jython'

In [80]:
word[0:2]+'Dra'

'PyDra'

In [81]:
word[0:2]+"pyt"+word[3:]

'Pypython'

In [82]:
x="bqbddbqojbedljnskndlknaqjdcowefbwbefdlncladljbcojwbeojcldlcljbwejbd"

In [83]:
len(x)

67

In [84]:
str('Rajkamal B Gowda')

'Rajkamal B Gowda'

In [85]:
str(1559.65)

'1559.65'

## Lists

In [86]:
squares = [1,4,9,16,25]

In [87]:
squares

[1, 4, 9, 16, 25]

In [88]:
friends=['sharu','bava','deepu','dhanu','chitte','halu','arju']

In [89]:
friends

['sharu', 'bava', 'deepu', 'dhanu', 'chitte', 'halu', 'arju']

In [90]:
squares[0] #list indexing returns new item

1

In [91]:
squares[3]

16

In [92]:
squares[0:] #list slicing returns new list

[1, 4, 9, 16, 25]

In [93]:
friends[1]

'bava'

In [94]:
friends[2:]

['deepu', 'dhanu', 'chitte', 'halu', 'arju']

In [95]:
friends[-1]

'arju'

In [96]:
friends[:-1]

['sharu', 'bava', 'deepu', 'dhanu', 'chitte', 'halu']

In [97]:
x=friends[2:]

In [98]:
x

['deepu', 'dhanu', 'chitte', 'halu', 'arju']

In [99]:
x=[2,3,5,8]
y=[3,4,9,12]

In [100]:
x+y

[2, 3, 5, 8, 3, 4, 9, 12]

In [101]:
x+[5,6]

[2, 3, 5, 8, 5, 6]

In [102]:
z=['raj','shaj','taj','uaj']

In [103]:
z+['shar','danny']

['raj', 'shaj', 'taj', 'uaj', 'shar', 'danny']

In [104]:
x+z

[2, 3, 5, 8, 'raj', 'shaj', 'taj', 'uaj']

In [105]:
z+y

['raj', 'shaj', 'taj', 'uaj', 3, 4, 9, 12]

In [106]:
x+z+y

[2, 3, 5, 8, 'raj', 'shaj', 'taj', 'uaj', 3, 4, 9, 12]

In [107]:
#lists are mutable

even_numbers=[0,2,4,6,8,10,11,14]

In [108]:
even_numbers

[0, 2, 4, 6, 8, 10, 11, 14]

In [109]:
even_numbers[6]=12

In [110]:
even_numbers

[0, 2, 4, 6, 8, 10, 12, 14]

In [111]:
x=even_numbers

In [112]:
x

[0, 2, 4, 6, 8, 10, 12, 14]

In [113]:
x.append(16)

In [114]:
x

[0, 2, 4, 6, 8, 10, 12, 14, 16]

In [115]:
x.append(5**8)

In [116]:
x

[0, 2, 4, 6, 8, 10, 12, 14, 16, 390625]

In [117]:
letters=['a','b','c','d','e','f','g']

In [118]:
letters[2:5]=['C','D','E']

In [119]:
letters

['a', 'b', 'C', 'D', 'E', 'f', 'g']

In [120]:
letters[:2]=['Raj',2]

In [121]:
letters

['Raj', 2, 'C', 'D', 'E', 'f', 'g']

In [122]:
letters[0:1]=[]

In [123]:
letters

[2, 'C', 'D', 'E', 'f', 'g']

In [124]:
letters[3:5]=[]

In [125]:
letters

[2, 'C', 'D', 'g']

In [126]:
letters[:]=[]

In [127]:
letters

[]

In [128]:
list=[2,5,4,8,9,8,6,1,3,4,9]

In [129]:
len(list)

11

In [130]:
nested_list=[['raj','kamal','data','science'],2,3,5,[2,5,4],[5,6,8,[7,'taj'],'lion']]

In [131]:
nested_list[0]

['raj', 'kamal', 'data', 'science']

In [132]:
nested_list[0][1]

'kamal'

In [133]:
nested_list[5][4]

'lion'

In [134]:
nested_list[5][3]

[7, 'taj']

In [135]:
nested_list[5][3][1]

'taj'

## If statement

In [136]:
x=int(input("Enter the value of x: "))

if x<0:
    x=0
    print("Negative number changed to zero")
elif x==0:
    print("It is zero")
elif x==1:
    print("One")
else:
    print("The number is more than one")

Enter the value of x: -5
Negative number changed to zero


In [137]:
password=str(input("Enter the password to unlock the room: "))

if password == 'rajkamal':
    print("The door is unlocked")
else:
    print("Your password is invalid")

Enter the password to unlock the room: rajkamal
The door is unlocked


## For statements

In [138]:
x=['cat','dog','rat','hend','cow']

In [139]:
for animals in x:
    print(animals)

cat
dog
rat
hend
cow


In [140]:
for animals in x: 
    print(x)

['cat', 'dog', 'rat', 'hend', 'cow']
['cat', 'dog', 'rat', 'hend', 'cow']
['cat', 'dog', 'rat', 'hend', 'cow']
['cat', 'dog', 'rat', 'hend', 'cow']
['cat', 'dog', 'rat', 'hend', 'cow']


In [141]:
for animals in x:
    print(len(animals))

3
3
3
4
3


In [142]:
for animals in x:
    print("raj")

raj
raj
raj
raj
raj


In [143]:
for animals in x:
    print(2**3)

8
8
8
8
8


In [144]:
for animals in x:
    print(animals,len(animals))

cat 3
dog 3
rat 3
hend 4
cow 3


In [145]:
for animals in x:
    print(animals,'length is',len(animals))

cat length is 3
dog length is 3
rat length is 3
hend length is 4
cow length is 3


In [146]:
words=['rat','datascience','laptop','king','independenceday']
for w in words[:]: #always use sllicing or else it may become an infinite loop
    if len(w)>8:
        words.insert(0,w)

In [147]:
words

['independenceday',
 'datascience',
 'rat',
 'datascience',
 'laptop',
 'king',
 'independenceday']

## Range function

In [148]:
for num in range(5):
    print(num)

0
1
2
3
4


In [149]:
for i in range(5):
    print("raj")

raj
raj
raj
raj
raj


In [150]:
for i in range(5,10):
    print(i)

5
6
7
8
9


In [151]:
for i in range(1,11,3):
    print(i)

1
4
7
10


In [152]:
for i  in range(-10,-100,-30):
    print(i)

-10
-40
-70


In [153]:
for i  in range(-10,-100,-20):
    print(i)

-10
-30
-50
-70
-90


In [154]:
a=['mary','sham','john','peter','rony','danny']

for i in range(len(a)):
    print(i,a[i])

0 mary
1 sham
2 john
3 peter
4 rony
5 danny


In [155]:
for i in range(2,2):
    print(i)                     #nothing executes

In [156]:
for i in range(2,3):
    print(i)  

2


## break and continue Statements, and else Clauses on Loops

In [158]:
n= int(input("Enter the number: "))
for x in range(2, n):
    if n % x == 0:
        print(n, "is not a prime number")
        break         #it breaks if condition is true
else:
    print(n, 'is a prime number')  # loop fell through without finding a factor

Enter the number: 25
25 is not a prime number


In [159]:
for n in range(2,15):
    for x in range(2,n):
        if n%x==0:
            print(n, "is not a prime number")
            break
    else:
            print(n,"is a prime number")

2 is a prime number
3 is a prime number
4 is not a prime number
5 is a prime number
6 is not a prime number
7 is a prime number
8 is not a prime number
9 is not a prime number
10 is not a prime number
11 is a prime number
12 is not a prime number
13 is a prime number
14 is not a prime number


In [160]:
for num in range(2, 10):
     if num % 2 == 0:
        print("Found an even number", num)    
        continue                                 #if condition is true loops back, or else jump to next statement
        print("Found a number", num)

Found an even number 2
Found an even number 4
Found an even number 6
Found an even number 8


## pass statements

The pass statement does nothing. It can be used when a statement is required syntactically but the program requires no action

In [162]:
n= int(input("Enter the number: "))
if n%2==0:
    print("Even")
else:
    pass

Enter the number: 5


In [163]:
class MyEmptyClass:
     pass

In [164]:
def initlog(*args):
     pass 

In [165]:
x=5
while x<5:
    pass

## Defining Functions

In [166]:
# write Fibonacci series up to n
                         
def fibonacci(n,x,y):
    a, b = x, y
    while a < n:
        print(a)
        a, b = b, a+b

In [167]:
fibonacci(15,1,1)

1
1
2
3
5
8
13


In [168]:
# write Fibonacci series up to n
                         
def fibonacci(n):
    a, b = 0, 1
    for i in range(n):
        print(a)
        a, b = b, a+b

In [169]:
fibonacci(20)

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181


In [170]:
def add(x,y):
    print(x+y)

In [171]:
add(25,26)

51


In [172]:
a=add

In [173]:
a(5,6)

11


### print fabonacci number from 1 to 100

In [174]:
a,b=0,1
while a<100:
    print(a)
    a,b=b,b+a

0
1
1
2
3
5
8
13
21
34
55
89


In [175]:
a,b=0,1
while a<1000:
    print(a)
    a,b=b,b+a

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987


In [176]:
#Return a list containing the Fibonacci series up to n.

def fib2(n):  
    result = []
    a, b = 0, 1
    while a < n:
        result.append(a)    
        a, b = b, a+b
    return result

In [177]:
fib2(1000)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]

### Default Argument Values

This example also introduces the 'in' keyword. This tests whether or not a sequence contains a certain value

In [180]:
def interview (question):
    x=str(input(question))
    if x in ('yes'):
        print(" Thanku sir")
    if x in ('No'):
        print("Why sir what happend?")

In [181]:
interview("Did you eat lunch?")

Did you eat lunch?yes
 Thanku sir


In [182]:
interview('Did you go to forest?')

Did you go to forest?No
Why sir what happend?


In [183]:
interview("Did you like barbeque?")

Did you like barbeque?no


In [184]:
def ask_ok(prompt,retries=4,reminder="Please try again!"):
    while True:
        ok=input(prompt)
        if ok in ('y','ye','yes'):
            return True
        if ok in ('n', 'no', 'nop', 'nope'):
            return False
        retries = retries - 1
        if retries < 0:
            raise ValueError('invalid user response')
        print(reminder)

In [185]:
ask_ok('Do you really want to quit?')

Do you really want to quit?y


True

In [186]:
ask_ok('Do you really want to quit?')

Do you really want to quit?n


False

In [188]:
ask_ok('Do you really want to quit?')

Do you really want to quit?why do you want
Please try again!
Do you really want to quit?what man?
Please try again!
Do you really want to quit?yes


True

In [189]:
def windows_password(password,retries=3,reminder="wrong password"):
    while True:
        hint_password=input(password)
        
        if hint_password == "Rajkamal":
            return('The windows has been unlocked')
        retries=retries-1
        if retries<0:
            raise ValueError('Your system has been locked')
        print(reminder)
    

In [190]:
windows_password('Open my password: ')

Open my password: huguub
wrong password
Open my password: jbjbbjb
wrong password
Open my password: hyvyvhv
wrong password
Open my password: ftcy


ValueError: Your system has been locked

In [191]:
windows_password('Open my password: ')

Open my password: Rajkamal


'The windows has been unlocked'

In [192]:
windows_password('Open my password: ',1)

Open my password: gugu
wrong password
Open my password: h


ValueError: Your system has been locked

In [193]:
windows_password('Open my password: ',1,'your password is wrong')

Open my password: hjubu
your password is wrong
Open my password: hubu


ValueError: Your system has been locked

In [194]:
y=input("Enter the number :")

Enter the number :5


In [195]:
def f(x=6):  #setting default value
    print(x)

In [196]:
f()                             #because default value has been set

6


In [197]:
f(5) 

5


In [198]:
x,y=2,3
def fun(arg1=x,arg2=y):
    print(arg1+arg2)

In [199]:
fun()

5


In [200]:
fun(5,4)

9


In [201]:
fun()

5


Important warning: The default value is evaluated only once. This makes a difference when the default is a mutable object such as a list, dictionary, or instances of most classes. For example, the following function accumulates the arguments passed to it on subsequent calls:



In [202]:
def f(a, L=[]):
    L.append(a)
    return L

In [203]:
f(1)

[1]

In [204]:
f(2)

[1, 2]

In [205]:
f('raj')

[1, 2, 'raj']

In [206]:
print(f('sharu'))

[1, 2, 'raj', 'sharu']


In [207]:
def f(x,L=[]):
    L.append(x)
    return L

In [208]:
f(2)

[2]

In [209]:
f(3)

[2, 3]

If you don’t want the default to be shared between subsequent calls, you can write the function like this instead:

In [210]:
def f(a, L=None):
    if L is None:
        L = []
    L.append(a)
    return L

In [211]:
f(2)

[2]

In [212]:
f(3)

[3]

In [213]:
f([3,4,3])

[[3, 4, 3]]

### Keyword Arguments

In [214]:
def parrot(voltage, state='a stiff', action='voom', type='Norwegian Blue'):
    print("-- This parrot wouldn't", action, end=' ')
    print("if you put", voltage, "volts through it.")
    print("-- Lovely plumage, the", type)
    print("-- It's", state, "!")

In [215]:
parrot(1000)                                          # 1 positional argument

-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !


In [216]:
parrot(voltage=1000)                                  # 1 keyword argument

-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !


In [217]:
parrot(voltage=1000000, action='VOOOOOM')             # 2 keyword arguments

-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !


In [218]:
parrot(action='VOOOOOM', voltage=1000000)             # 2 keyword arguments

-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !


In [219]:
parrot('a million', 'bereft of life', 'jump')         # 3 positional arguments

-- This parrot wouldn't jump if you put a million volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's bereft of life !


In [220]:
parrot('a thousand', state='pushing up the daisies')  # 1 positional, 1 keyword

-- This parrot wouldn't voom if you put a thousand volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's pushing up the daisies !


In [221]:
 def function(a):
    pass

 function(0, a=0)

TypeError: function() got multiple values for argument 'a'

When a final formal parameter of the form **name is present, it receives a dictionary (see Mapping Types — dict) containing all keyword arguments except for those corresponding to a formal parameter. This may be combined with a formal parameter of the form *name (described in the next subsection) which receives a tuple containing the positional arguments beyond the formal parameter list. (*name must occur before **name.) For example, if we define a function like this:

In [222]:
def cheeseshop(kind, *arguments, **keywords):
    print("-- Do you have any", kind, "?")
    print("-- I'm sorry, we're all out of", kind)
    for arg in arguments:
        print(arg)
    print("-" * 40)
    for kw in keywords:
        print(kw, ":", keywords[kw])

In [223]:
cheeseshop("Limburger", "It's very runny, sir.",
           "It's really very, VERY runny, sir.",
           shopkeeper="Michael Palin",
           client="John Cleese",
           sketch="Cheese Shop Sketch")

-- Do you have any Limburger ?
-- I'm sorry, we're all out of Limburger
It's very runny, sir.
It's really very, VERY runny, sir.
----------------------------------------
shopkeeper : Michael Palin
client : John Cleese
sketch : Cheese Shop Sketch


In [236]:
def parrot(voltage, state='a stiff', action='voom'):
        print("-- This parrot wouldn't", action, end=' ')
        print("if you put", voltage, "volts through it.", end=' ')
        print("E's", state, "!")

In [237]:
d = {"voltage": "four million", "state": "bleedin' demised", "action": "VOOM"}

In [238]:
parrot(**d)

-- This parrot wouldn't VOOM if you put four million volts through it. E's bleedin' demised !


### Lambda Expressions

Anonymous function or a function with no name

In [256]:
def add(a,b):
    return a+b

In [257]:
add(2,3)

5

In [258]:
addition=lambda x,y:x+y

In [259]:
addition(2,3)

5

In [266]:
def even_num(x):
    if x%2==0:
        return True
    else:
        return False

In [267]:
even_num(5)

False

In [268]:
even_num(2)

True

In [269]:
lambda x:x%2==0

<function __main__.<lambda>(x)>

In [270]:
even_odd=lambda x:x%2==0

In [271]:
even_odd(5)

False

In [272]:
even_odd(2)

True

In [273]:
operation = lambda x,y,z:(x+y)*z

In [274]:
operation(2,3,4)

20

In [275]:
def func(n):
    return lambda x:x+n

In [276]:
y= func(2)

In [277]:
y(2)

4

In [278]:
def incriment(n):
    return lambda x:x+n

In [279]:
x=incriment(15)

In [280]:
x(5)

20

In [281]:
x(2)

17

In [282]:
def decriment(n):
    return lambda x:n-x

In [283]:
f= decriment(25)

In [284]:
f(5)

20

In [285]:
f(12)

13

In [286]:
f(10)

15

The above example uses a lambda expression to return a function. Another use is to pass a small function as an argument:

In [287]:
 pairs = [(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')]

In [288]:
pairs.sort(key= lambda pair:pair[1])

In [289]:
pairs

[(4, 'four'), (1, 'one'), (3, 'three'), (2, 'two')]

## Data Structures

### More on lists

In [290]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']

In [291]:
fruits.count('apple')

2

In [292]:
fruits.count('orange')

1

In [293]:
fruits.count('tangerine')

0

In [294]:
fruits.index('banana')

3

In [295]:
fruits.index('banana',4) # Find next banana starting a position 4

6

In [296]:
fruits.reverse()

In [297]:
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']

In [298]:
fruits.append('grape')

In [299]:
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange', 'grape']

In [300]:
fruits.sort()

In [301]:
fruits

['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange', 'pear']

In [302]:
fruits.pop()

'pear'

In [303]:
fruits

['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange']

In [304]:
fruits.pop(1)

'apple'

In [305]:
fruits

['apple', 'banana', 'banana', 'grape', 'kiwi', 'orange']

In [306]:
fruits.pop(2)

'banana'

In [307]:
fruits

['apple', 'banana', 'grape', 'kiwi', 'orange']

### Using Lists as Stacks

In [308]:
stack = [3, 4, 5]

In [309]:
stack.append(6)

In [310]:
stack.append(7)

In [311]:
stack.append(8)

In [312]:
stack

[3, 4, 5, 6, 7, 8]

In [313]:
stack.pop()

8

In [314]:
stack.pop()

7

In [315]:
stack

[3, 4, 5, 6]

### Using Lists as Queues

To implement a queue, use collections.deque which was designed to have fast appends and pops from both ends. For example:

In [316]:
from collections import deque

In [317]:
queue = deque(["Eric", "John", "Michael"])

In [318]:
queue.append("Terry")

In [319]:
queue.append("raju")

In [320]:
queue.append("sharu")

In [321]:
queue

deque(['Eric', 'John', 'Michael', 'Terry', 'raju', 'sharu'])

In [322]:
queue.popleft()

'Eric'

In [323]:
queue.popleft()

'John'

In [324]:
queue

deque(['Michael', 'Terry', 'raju', 'sharu'])

### List Comprehensions

List comprehensions provide a concise way to create lists. Common applications are to make new lists where each element is the result of some operations applied to each member of another sequence or iterable, or to create a subsequence of those elements that satisfy a certain condition.

In [325]:
squares = []

In [326]:
for x in range(10):
     squares.append(x**2)

In [327]:
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [328]:
x

9

Note that this creates (or overwrites) a variable named x that still exists after the loop completes. We can calculate the list of squares without any side effects using:

In [329]:
squares = [x**2 for x in range(10)]

In [330]:
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

A list comprehension consists of brackets containing an expression followed by a for clause, then zero or more for or if clauses. The result will be a new list resulting from evaluating the expression in the context of the for and if clauses which follow it. For example, this listcomp combines the elements of two lists if they are not equal:

In [331]:
[(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [332]:
combs = []
for x in [1,2,3]:
     for y in [3,1,4]:
            if x != y:
                combs.append((x, y))

In [333]:
combs

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [334]:
vec = [-4, -2, 0, 2, 4]

In [335]:
# create a new list with the values doubled
 [x*2 for x in vec]

IndentationError: unexpected indent (<ipython-input-335-e1b4abd29e6a>, line 2)

In [336]:
# filter the list to exclude negative numbers
[x for x in vec if x >= 0]

[0, 2, 4]

In [337]:
# apply a function to all the elements
[abs(x) for x in vec]

[4, 2, 0, 2, 4]

In [338]:
# call a method on each element
freshfruit = ['  banana', '  loganberry ', 'passion fruit  ']
[weapon.strip() for weapon in freshfruit]

['banana', 'loganberry', 'passion fruit']

In [339]:
# create a list of 2-tuples like (number, square)
[(x, x**2) for x in range(6)]

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]

In [340]:
# the tuple must be parenthesized, otherwise an error is raised
[x, x**2 for x in range(6)]

SyntaxError: invalid syntax (<ipython-input-340-702d12ece8a4>, line 2)

In [341]:
# flatten a list using a listcomp with two 'for'
vec = [[1,2,3], [4,5,6], [7,8,9]]
[num for elem in vec for num in elem]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [342]:
from math import pi
[str(round(pi, i)) for i in range(1, 6)]

['3.1', '3.14', '3.142', '3.1416', '3.14159']

### Nested List Comprehensions

The initial expression in a list comprehension can be any arbitrary expression, including another list comprehension.

Consider the following example of a 3x4 matrix implemented as a list of 3 lists of length 4:

In [343]:
matrix = [
     [1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12],
 ]

In [344]:
matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

The following list comprehension will transpose rows and columns:

In [345]:
[[row[i] for row in matrix] for i in range(4)]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

As we saw in the previous section, the nested listcomp is evaluated in the context of the for that follows it, so this example is equivalent to:

In [346]:
transposed = []

In [347]:
for i in range(4):
    transposed.append([row[i] for row in matrix])

In [348]:
transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

which, in turn, is the same as:

In [349]:
transposed = []
for i in range(4):
# the following 3 lines implement the nested listcomp
    transposed_row = []
    for row in matrix:
        transposed_row.append(row[i])
    transposed.append(transposed_row)


In [350]:
transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

### The del statement

In [351]:
a = [-1, 1, 66.25, 333, 333, 1234.5]

In [352]:
del a[0]

In [353]:
a

[1, 66.25, 333, 333, 1234.5]

In [354]:
del a[2:4]

In [355]:
a

[1, 66.25, 1234.5]

In [356]:
del a[:]

In [357]:
a

[]

In [358]:
del a

In [359]:
a

NameError: name 'a' is not defined

### Tuples and Sequences

In [360]:
t = 12345, 54321, 'hello!'

In [361]:
t[0]

12345

In [362]:
t

(12345, 54321, 'hello!')

In [363]:
# Tuples may be nested:
u = t, (1, 2, 3, 4, 5)

In [364]:
u

((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))

In [365]:
# Tuples are immutable:
t[0] = 88888

TypeError: 'tuple' object does not support item assignment

In [366]:
# but they can contain mutable objects:
v = ([1, 2, 3], [3, 2, 1])

In [367]:
v

([1, 2, 3], [3, 2, 1])

In [368]:
empty = ()

In [369]:
singleton = 'hello',    # <-- note trailing comma

In [370]:
len(empty)

0

In [371]:
len(singleton)

1

In [372]:
singleton

('hello',)

The statement t = 12345, 54321, 'hello!' is an example of tuple packing: the values 12345, 54321 and 'hello!' are packed together in a tuple. The reverse operation is also possible:

In [373]:
x, y, z = t

In [374]:
x

12345

In [375]:
y

54321

In [376]:
z

'hello!'

In [377]:
t

(12345, 54321, 'hello!')

This is called, appropriately enough, sequence unpacking and works for any sequence on the right-hand side. Sequence unpacking requires that there are as many variables on the left side of the equals sign as there are elements in the sequence. Note that multiple assignment is really just a combination of tuple packing and sequence unpacking.

### Sets

Python also includes a data type for sets. A set is an unordered collection with no duplicate elements. Basic uses include membership testing and eliminating duplicate entries. Set objects also support mathematical operations like union, intersection, difference, and symmetric difference.

Curly braces or the set() function can be used to create sets. Note: to create an empty set you have to use set(), not {}; the latter creates an empty dictionary, a data structure that we discuss in the next section.

Here is a brief demonstration:

In [378]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}

In [379]:
print(basket) 

{'apple', 'banana', 'orange', 'pear'}


In [380]:
'orange' in basket                 # fast membership testing

True

In [381]:
'crabgrass' in basket

False

In [382]:
# Demonstrate set operations on unique letters from two words

In [383]:
a = set('abracadabra')
b = set('alacazam')

In [384]:
a                                  # unique letters in a

{'a', 'b', 'c', 'd', 'r'}

In [385]:
a - b                              # letters in a but not in b

{'b', 'd', 'r'}

In [386]:
a | b                              # letters in a or b or both

{'a', 'b', 'c', 'd', 'l', 'm', 'r', 'z'}

In [387]:
a & b                              # letters in both a and b

{'a', 'c'}

In [388]:
a ^ b                              # letters in a or b but not both

{'b', 'd', 'l', 'm', 'r', 'z'}

Similarly to list comprehensions, set comprehensions are also supported:

In [389]:
a = {x for x in 'abracadabra' if x not in 'abc'}

In [390]:
a

{'d', 'r'}

### Dictionaries

In [391]:
tel = {'jack': 4098, 'sape': 4139}

In [392]:
tel['guido'] = 4127

In [393]:
tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}

In [394]:
tel['jack']

4098

In [395]:
del tel['sape']

In [396]:
tel

{'jack': 4098, 'guido': 4127}

In [397]:
tel['irv'] = 4127

In [398]:
tel

{'jack': 4098, 'guido': 4127, 'irv': 4127}

In [399]:
list(tel)

TypeError: 'list' object is not callable

In [400]:
sorted(tel)

['guido', 'irv', 'jack']

In [401]:
'guido' in tel

True

In [402]:
'jack' not in tel

False

The dict() constructor builds dictionaries directly from sequences of key-value pairs:

In [403]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'sape': 4139, 'guido': 4127, 'jack': 4098}

In addition, dict comprehensions can be used to create dictionaries from arbitrary key and value expressions:

In [404]:
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

When the keys are simple strings, it is sometimes easier to specify pairs using keyword arguments:

In [405]:
dict(sape=4139, guido=4127, jack=4098)

{'sape': 4139, 'guido': 4127, 'jack': 4098}

### Looping Techniques

In [406]:
knights = {'gallahad': 'the pure', 'robin': 'the brave'}

In [407]:
for k, v in knights.items():
    print(k, v)

gallahad the pure
robin the brave


When looping through a sequence, the position index and corresponding value can be retrieved at the same time using the enumerate() function.

In [408]:
for i, v in enumerate(['tic', 'tac', 'toe']):
     print(i, v)

0 tic
1 tac
2 toe


To loop over two or more sequences at the same time, the entries can be paired with the zip() function

In [409]:
questions = ['name', 'quest', 'favorite color']

In [410]:
answers = ['lancelot', 'the holy grail', 'blue']

In [411]:
for q, a in zip(questions, answers):
     print('What is your {0}?  It is {1}.'.format(q, a))

What is your name?  It is lancelot.
What is your quest?  It is the holy grail.
What is your favorite color?  It is blue.


To loop over a sequence in reverse, first specify the sequence in a forward direction and then call the reversed() function.

In [412]:
for i in reversed(range(1, 10, 2)):
     print(i)

9
7
5
3
1


To loop over a sequence in sorted order, use the sorted() function which returns a new sorted list while leaving the source unaltered.

In [413]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']

In [414]:
for f in sorted(set(basket)):
     print(f)

apple
banana
orange
pear


It is sometimes tempting to change a list while you are looping over it; however, it is often simpler and safer to create a new list instead.

In [415]:
import math

In [416]:
 raw_data = [56.2, float('NaN'), 51.7, 55.3, 52.5, float('NaN'), 47.8]

In [417]:
filtered_data = []

In [418]:
for value in raw_data:
     if not math.isnan(value):
            filtered_data.append(value)

In [419]:
filtered_data

[56.2, 51.7, 55.3, 52.5, 47.8]

### More on Conditions

In [420]:
string1, string2, string3 = '', 'Trondheim', 'Hammer Dance'

In [421]:
non_null = string1 or string2 or string3

In [422]:
non_null

'Trondheim'

### Comparing Sequences and Other Types

In [423]:
(1, 2, 3)              < (1, 2, 4)

True

In [424]:
'ABC' < 'C' < 'Pascal' < 'Python'


True

In [425]:
(1, 2, 3, 4)           < (1, 2, 4)

True

In [426]:
(1, 2)                 < (1, 2, -1)

True

In [427]:
(1, 2, 3)             == (1.0, 2.0, 3.0)

True

In [428]:
(1, 2, ('aa', 'ab'))   < (1, 2, ('abc', 'a'), 4)

True

## Map functions in python

In [453]:
def function_name(x):
    if x%2==0:
        return("The {} is even".format(x))
    else:
        return("The {} is odd".format(x))

In [454]:
function_name(2)

'The 2 is even'

In [455]:
function_name(3)

'The 3 is odd'

In [456]:
function_name([2,3]) #we cannot perform it on multiple values, so we can use map function

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [457]:
lst=[2,3,4,5,6]

In [488]:
y=map(function_name,lst)

In [468]:
for i in y:
    print(i)

The 2 is even
The 3 is odd
The 4 is even
The 5 is odd
The 6 is even


In [479]:
tuple(y)

('The 2 is even',
 'The 3 is odd',
 'The 4 is even',
 'The 5 is odd',
 'The 6 is even')

In [487]:
set(y)

{'The 2 is even',
 'The 3 is odd',
 'The 4 is even',
 'The 5 is odd',
 'The 6 is even'}

In [490]:
print(y)

## Filert function

In [501]:
def even(x):
    if x%2==0:
        return True
    else:
        return False

In [502]:
lst=[2,3,4,5,6]

In [497]:
filter(even,lst)

In [499]:
set(filter(even,lst))

{2, 4, 6}

In [510]:
list(map(even,lst))

[True, False, True, False, True]

In [511]:
list(filter(even,lst)) #it returns only which satisfies condition

[2, 4, 6]

## Oops concept

In [527]:
class car:
    pass

In [528]:
car()

In [529]:
cr=car() #creating instance

In [530]:
cr.windows=4
cr.engyne_type='Petrol'

In [531]:
print(cr.windows)

4


In [532]:
print(cr.engyne_type)

Petrol


In [533]:
cr2=car()

In [534]:
cr2.windows=2

In [535]:
print(cr2.windows)

2


In [537]:
dir(car)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']

In [538]:
class car:
    def __init__(self,windows,door,engine_type):
        self.windows=windows
        self.door=door
        self.engine_type=engine_type
    

In [539]:
car1=car(2,3,"petrol")

In [540]:
car1

In [544]:
print(car1.windows)
print(car1.door)
print(car1.engine_type)

2
3
petrol


In [546]:
car2=car(4,5,"diesel")

In [547]:
print(car2.windows)
print(car2.door)
print(car2.engine_type)

4
5
diesel


In [552]:
class car:
    def __init__(self,windows,door,engine_type):
        self.windows=windows
        self.door=door
        self.engine_type=engine_type
    def self_driving(self):
        print("This car's engine type is {}".format(self.engine_type))

In [553]:
car3=car(2,3,"Diesel")

In [554]:
car3.self_driving

<bound method car.self_driving of <__main__.car object at 0x000001EA0D11FC18>>

In [555]:
car3.self_driving()

This car's engine type is Diesel


# *******************************************************